/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package maja.view.kategorije;

import maja.view.*;
import maja.view.operateri.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import maja.controller.ObradaOperater;
import maja.model.Operater;
import maja.utility.Pomocno;
import maja.view.operateri.PozivateljPromjenaLozinke;
import maja.view.operateri.PromjenaLozinke;
import maja.view.tockeInteresa.CRUD.CRUD;
import maja.view.tockaInteresa.ProzorTockaInteresa;

/**
 *
 * @author Maja
 */
public class AutorizacijaKategorije extends javax.swing.JFrame{

    private ObradaOperater obradaOperater;
    private Operater oznaceniOperater;
    
    public AutorizacijaKategorije() {
        initComponents();
        obradaOperater=new ObradaOperater();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        korisnickoIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lozinka = new javax.swing.JPasswordField();
        gumbAutoriziraj = new javax.swing.JButton();
        poruka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Authorization");

        jLabel1.setText("User name");

        korisnickoIme.setText("mklajic");

        jLabel2.setText("Password");

        lozinka.setText("m");

        gumbAutoriziraj.setText("Authorize!");
        gumbAutoriziraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbAutorizirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(korisnickoIme))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lozinka))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(gumbAutoriziraj, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addComponent(poruka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(poruka, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(korisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(gumbAutoriziraj)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gumbAutorizirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gumbAutorizirajActionPerformed
             Operater t = obradaOperater.getOperater(korisnickoIme.getText(), Pomocno.generirajMD5(lozinka.getPassword()));
        
        if(t==null){
            poruka.setText("Incorrect username or password");
        }else{
            
            new CRUDKategorije().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_gumbAutorizirajActionPerformed

  private void korisnickoImeKeyPressed(java.awt.event.KeyEvent evt) {                                         
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           if(this.lozinka.getPassword().length>0){
               gumbAutorizirajActionPerformed(null);
           }else{
               this.lozinka.requestFocus();
           }
       }
    }                                        

    private void lozinkaKeyPressed(java.awt.event.KeyEvent evt) {                                   
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           if(this.korisnickoIme.getText().length()>0){
               gumbAutorizirajActionPerformed(null);
           }else{
               this.korisnickoIme.requestFocus();
           }
       }
    }      
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gumbAutoriziraj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField korisnickoIme;
    private javax.swing.JPasswordField lozinka;
    private javax.swing.JLabel poruka;
    // End of variables declaration//GEN-END:variables

       
  
}
