/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package maja.view.tockeInteresa.CRUD;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import maja.controller.ObradaKategorija;
import maja.controller.ObradaTockaInteresa;
import maja.model.Kategorije;
import maja.model.TockaInteresa;
import net.atlanticbb.tantlinger.shef.HTMLEditorPane;

/**
 *
 * @author Maja
 */
public class DetaljiCRUD extends javax.swing.JFrame {

    private TockaInteresa oznacenaStavka;
    private ObradaTockaInteresa obradaTockaInteresa;
    private boolean promjena=false;
    private Kategorije kategorije;
    private ObradaKategorija obradaKategorija;
    private HTMLEditorPane html;
    private CRUD crud;

    public TockaInteresa getOznacenaStavka() {
        return oznacenaStavka;
    }

    public void setOznacenaStavka(TockaInteresa oznacenaStavka) {
         this.oznacenaStavka=oznacenaStavka;
        if(oznacenaStavka!=null){
            promjena=true;
            
         this.naziv.setText(oznacenaStavka.getNaziv());
         this.adresa.setText(oznacenaStavka.getAdresa());
         this.putanja.setText(oznacenaStavka.getPutanja());
         this.html.setText(oznacenaStavka.getKratakOpis());
         
         DefaultListModel<Kategorije> mk = new DefaultListModel<>();
        for (Kategorije k : oznacenaStavka.getKategorije()) {
            mk.addElement(k);
        }
        this.dodjeljeneKategorije.setModel(mk);
        
                
       
 
    }
    }
    
   
    public DetaljiCRUD(CRUD crud) {
        initComponents();
        obradaKategorija= new ObradaKategorija();
        obradaTockaInteresa= new ObradaTockaInteresa();
        ucitajKategorije();
        html = new HTMLEditorPane();
        html.setSize(kratakOpis.getSize());
        kratakOpis.add(html);
        this.crud=crud;
        DefaultListModel<Kategorije> m = new DefaultListModel<>();
        this.dodjeljeneKategorije.setModel(m);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        putanja = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        adresa = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        naziv = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        kratakOpis = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        popisKategorija = new javax.swing.JList();
        akcijaDodaj = new javax.swing.JButton();
        akcijaUkloni = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dodjeljeneKategorije = new javax.swing.JList();
        spremi = new javax.swing.JButton();
        odustaniž = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Details ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        putanja.setColumns(20);
        putanja.setRows(5);
        putanja.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        putanja.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane5.setViewportView(putanja);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        adresa.setColumns(20);
        adresa.setRows(5);
        adresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        adresa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setViewportView(adresa);

        jLabel5.setText("URL");

        jLabel4.setText("Address");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        naziv.setColumns(20);
        naziv.setRows(5);
        naziv.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane4.setViewportView(naziv);

        jLabel2.setText("Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kratakOpisLayout = new javax.swing.GroupLayout(kratakOpis);
        kratakOpis.setLayout(kratakOpisLayout);
        kratakOpisLayout.setHorizontalGroup(
            kratakOpisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        kratakOpisLayout.setVerticalGroup(
            kratakOpisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jLabel3.setText("Short description");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Categories"));

        jScrollPane2.setViewportView(popisKategorija);

        akcijaDodaj.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        akcijaDodaj.setText("------>");
        akcijaDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaDodajActionPerformed(evt);
            }
        });

        akcijaUkloni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        akcijaUkloni.setText("<-----");
        akcijaUkloni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaUkloniActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(dodjeljeneKategorije);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(akcijaDodaj)
                    .addComponent(akcijaUkloni, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(akcijaDodaj)
                        .addGap(33, 33, 33)
                        .addComponent(akcijaUkloni))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spremi.setText("Save");
        spremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spremiActionPerformed(evt);
            }
        });

        odustaniž.setText("Dismiss");
        odustaniž.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odustanižActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spremi, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(odustaniž, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(kratakOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kratakOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spremi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(odustaniž, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void odustanižActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odustanižActionPerformed
       this.dispose();
    }//GEN-LAST:event_odustanižActionPerformed

    private void akcijaDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaDodajActionPerformed
         List<Kategorije> l = this.popisKategorija.getSelectedValuesList();
        DefaultListModel<Kategorije> m = (DefaultListModel<Kategorije>) this.dodjeljeneKategorije.getModel();
        boolean postoji;
        for (Kategorije kategorije : l) {
           postoji=false;
           for(int i=0; i<m.getSize(); i++){
               if(kategorije.getSifra()==m.get(i).getSifra()){
                   postoji=true;
               }
           }
           if(!postoji){
               m.addElement(kategorije);
           }
        }
    }//GEN-LAST:event_akcijaDodajActionPerformed

    private void akcijaUkloniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaUkloniActionPerformed
         List<Kategorije> l = this.dodjeljeneKategorije.getSelectedValuesList();
        DefaultListModel<Kategorije> m = (DefaultListModel<Kategorije>) this.dodjeljeneKategorije.getModel();
        for (Kategorije kategorije : l) {
            for(int i=0; i<m.getSize();i++){
                if(m.get(i).getSifra()==kategorije.getSifra()){
                    m.removeElementAt(i);
                    break;
                }
            }
        }
    }//GEN-LAST:event_akcijaUkloniActionPerformed

    private void spremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spremiActionPerformed
//        if(obradaTockaInteresa.provjeraNazivaUnos(this.naziv.getText())){
//            JOptionPane.showMessageDialog(rootPane,"Point of interest with the same name already exists!","Error",JOptionPane.ERROR_MESSAGE);
//            this.naziv.requestFocus();
//            return;
//        }
        if(naziv.getText().trim().length()==0){
            JOptionPane.showMessageDialog(rootPane,"Name field is mandatory!","Error",JOptionPane.ERROR_MESSAGE);
            this.naziv.requestFocus();
            return;
        }
         if(adresa.getText().trim().length()==0){
            JOptionPane.showMessageDialog(rootPane,"Address field is mandatory!","Errorr",JOptionPane.ERROR_MESSAGE);
            this.adresa.requestFocus();
            return;
        }
         if(html.getText().trim().length()==0){
            JOptionPane.showMessageDialog(rootPane,"Short description is mandatory!","Error",JOptionPane.ERROR_MESSAGE);
            this.kratakOpis.requestFocus();
            return;
        }
         if(putanja.getText().trim().length()==0){
            JOptionPane.showMessageDialog(rootPane,"URL is mandatory!","Errorr",JOptionPane.ERROR_MESSAGE);
            this.putanja.requestFocus();
            return;
        }
         if(!promjena){
            oznacenaStavka = new TockaInteresa();
        }
         
         oznacenaStavka.setNaziv(naziv.getText());
         oznacenaStavka.setAdresa(this.adresa.getText());
          oznacenaStavka.setPutanja(this.putanja.getText());
          oznacenaStavka.setKratakOpis(this.html.getText());
          
          List<Kategorije> l = new ArrayList<>();
        DefaultListModel<Kategorije> m = (DefaultListModel<Kategorije>)this.dodjeljeneKategorije.getModel();
        for(int i = 0; i<m.getSize(); i++){
            l.add(m.getElementAt(i));
        }
        oznacenaStavka.setKategorije(l);
       
       if(!promjena){
           oznacenaStavka = obradaTockaInteresa.dodaj(oznacenaStavka);
          
       }
       else{
           obradaTockaInteresa.promjeni(oznacenaStavka);
           
       }
               
       
       this.dispose();
       crud.ucitajPodatke();
    }//GEN-LAST:event_spremiActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea adresa;
    private javax.swing.JButton akcijaDodaj;
    private javax.swing.JButton akcijaUkloni;
    private javax.swing.JList dodjeljeneKategorije;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel kratakOpis;
    private javax.swing.JTextArea naziv;
    private javax.swing.JButton odustaniž;
    private javax.swing.JList popisKategorija;
    private javax.swing.JTextArea putanja;
    private javax.swing.JButton spremi;
    // End of variables declaration//GEN-END:variables

    private void ucitajKategorije() {
        List<Kategorije> l = obradaKategorija.getKategorije("");
       
        DefaultListModel<Kategorije> m = 
                new DefaultListModel<>();
        for(Kategorije k : l){
            m.addElement(k);
        }
       
        this.popisKategorija.setModel(m); 
        
    }

    
}
