/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package maja.view.operateri;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import maja.controller.ObradaOperater;
import maja.model.Operater;
import maja.utility.Pomocno;

/**
 *
 * @author Maja
 */
public class PromjenaLozinke extends javax.swing.JFrame {

   private Operater operater;
private PozivateljPromjenaLozinke pozivatelj;
    
    
    public PromjenaLozinke(Operater operater, PozivateljPromjenaLozinke pozivatelj) {
        initComponents();
        this.operater=operater;
        poruka.setText(poruka.getText() + operater.getImePrezime());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
           this.pozivatelj=pozivatelj;
    }

    

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poruka = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stara = new javax.swing.JPasswordField();
        nova = new javax.swing.JPasswordField();
        ponovoNova = new javax.swing.JPasswordField();
        promjeni = new javax.swing.JButton();
        porukaPromjena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Password change");

        poruka.setText("User: ");

        jLabel1.setText("Old password");

        jLabel2.setText("New password");

        jLabel3.setText("New password again");

        promjeni.setText("Change");
        promjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promjeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(porukaPromjena)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(promjeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(poruka)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ponovoNova, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nova, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(stara, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(poruka)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ponovoNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(promjeni, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(porukaPromjena)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void promjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promjeniActionPerformed
        porukaPromjena.setText("");
        if(stara.getPassword().length==0 ||
            nova.getPassword().length==0 ||
            ponovoNova.getPassword().length==0 ){
            porukaPromjena.setText("You have to fill out all 3 fields!");
            return;
        }

        if(!operater.getLozinka().
            equals(Pomocno.
                generirajMD5(stara.getPassword()))){
            porukaPromjena.setText("Old password don't match!");
            return;
        }

        if(!java.util.Arrays.equals(nova.getPassword(), ponovoNova.getPassword())){
            porukaPromjena.setText("New password don't metch repeated password!");
            return;
        }

        if(java.util.Arrays.equals(nova.getPassword(), stara.getPassword())){
            porukaPromjena.setText("New Password Must Be Different Than Your Old Password!");
            return;
        }

        //ovdje još mogu doći kontrole
        //kvalitete lozinke
        //min 8 znakova, mala velika slova, brojevi i interpukcijski znakovi

        //sve ok za promjeniti u bazi
        operater.setLozinka(Pomocno.generirajMD5(nova.getPassword()));

        ObradaOperater op = new ObradaOperater();
        if(op.promjeni(operater)){
            JOptionPane.showMessageDialog(rootPane,"Password successfully changed","Message",JOptionPane.PLAIN_MESSAGE);
            pozivatelj.nakonPromjene();
            dispose();
        }
        else{
            porukaPromjena.setText("Error, password is not changed. Try again!");
        }

    }//GEN-LAST:event_promjeniActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField nova;
    private javax.swing.JPasswordField ponovoNova;
    private javax.swing.JLabel poruka;
    private javax.swing.JLabel porukaPromjena;
    private javax.swing.JButton promjeni;
    private javax.swing.JPasswordField stara;
    // End of variables declaration//GEN-END:variables
}
